# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='second_name',
        ),
    ]
