# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20170903_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='died',
            field=models.DateField(blank=True, null=True),
        ),
    ]
