# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20170903_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={},
        ),
    ]
