# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_auto_20170903_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
