# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_actor_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['-updated', '-added']},
        ),
    ]
