# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_origin', models.CharField(blank=True, max_length=100)),
                ('title_cs', models.CharField(blank=True, max_length=100)),
                ('release_year', models.IntegerField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(blank=True, max_length=120)),
                ('csfd', models.URLField(max_length=100)),
                ('imdb', models.URLField(max_length=100)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'movies',
            },
        ),
    ]
