# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import movies.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100, validators=[movies.validators.validate_title_en])),
                ('title_origin', models.CharField(blank=True, max_length=100)),
                ('title_cz', models.CharField(blank=True, max_length=100)),
                ('release_year', models.IntegerField(validators=[movies.validators.validate_release_year])),
                ('length', models.IntegerField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('csfd', models.URLField(max_length=100)),
                ('imdb', models.URLField(max_length=100)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True)),
                ('genre', models.ManyToManyField(to='movies.Genre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'movies',
            },
        ),
    ]
