# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
