# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
