# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20170902_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='length',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
