# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movies_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
