# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20170902_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
