# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import movies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=120, validators=[movies.validators.validate_genre]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(validators=[movies.validators.validate_release_year]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_en',
            field=models.CharField(max_length=100, validators=[movies.validators.validate_title_en]),
        ),
    ]
