# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
    ]
