# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import movies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20170903_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, help_text='Separate by comma', max_length=120, validators=[movies.validators.validate_genre]),
        ),
    ]
