# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import movies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20170903_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title_cs',
            new_name='title_cz',
        ),
        migrations.AddField(
            model_name='movie',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=120, validators=[movies.validators.validate_genre]),
        ),
    ]
